
development:
  stripe_secret_key: 'sk_test_51JKQJgKZmf28OdEIXqpvisOhoisKsxpmYXtEtAMGcojdQv1FNQFPtvOPSdxX3EavnV0cBDAmJ9n27V0DJDRQvDkI00Yf7l1QVz'
  stripe_publishable_key: 'pk_test_51JKQJgKZmf28OdEIOkh0Vlt2ftSQfN5XRhnXovJMbDHK4y9ONxyIDeE31uGh5rdnTLcdHHRwHEExkMpVdZjxTLaD00ucCi0hDb'

production:
  stripe_secret_key: 'sk_test_51JKQJgKZmf28OdEIXqpvisOhoisKsxpmYXtEtAMGcojdQv1FNQFPtvOPSdxX3EavnV0cBDAmJ9n27V0DJDRQvDkI00Yf7l1QVz'
  stripe_publishable_key: 'pk_test_51JKQJgKZmf28OdEIOkh0Vlt2ftSQfN5XRhnXovJMbDHK4y9ONxyIDeE31uGh5rdnTLcdHHRwHEExkMpVdZjxTLaD00ucCi0hDb'
